

site_name: Documentação
site_description: Repositório da disciplina EPS/MDS
repo_url: https://github.com/parlamentaqui/documentation
site_dir: site
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  

  palette:
    primary: teal
    accent: brown
    language: 'pt'

plugins:
  - search

page:
- Home: 'docs/index.md'
